FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends iproute2 iputils-ping tzdata procps && \
    rm -rf /var/lib/apt/lists/* && \
    pip install c104==2.2.1


COPY docker/init.sh /gns3/init.sh
COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh /gns3/init.sh
COPY docker/master.py /app/master.py
WORKDIR /app

ENV HOST_IP=10.0.0.11
ENV PEERS="10.0.0.12 10.0.0.13"

ENTRYPOINT ["/entrypoint.sh"]
CMD ["python", "master.py"]